// SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause)
//
// THIS FILE IS AUTOGENERATED BY CARGO-LIBBPF-GEN!

pub use self::imp::*;

#[allow(renamed_and_removed_lints)]
#[allow(dead_code)]
#[allow(non_snake_case)]
#[allow(non_camel_case_types)]
#[allow(clippy::absolute_paths)]
#[allow(clippy::upper_case_acronyms)]
#[allow(clippy::zero_repeat_side_effects)]
#[warn(single_use_lifetimes)]
mod imp {
    #[allow(unused_imports, clippy::wildcard_imports)]
    use super::*;
    use libbpf_rs::libbpf_sys;
    use libbpf_rs::skel::OpenSkel;
    use libbpf_rs::skel::Skel;
    use libbpf_rs::skel::SkelBuilder;
    use libbpf_rs::AsRawLibbpf as _;
    use libbpf_rs::MapCore as _;
    fn build_skel_config(
    ) -> libbpf_rs::Result<libbpf_rs::__internal_skel::ObjectSkeletonConfig<'static>> {
        let mut builder = libbpf_rs::__internal_skel::ObjectSkeletonConfigBuilder::new(DATA);
        builder
            .name("tproxy_bpf")
            .map("tproxy_b.rodata", true)
            .prog("tproxy");
        builder.build()
    }
    pub struct OpenTproxyMaps<'obj> {
        pub rodata: libbpf_rs::OpenMapMut<'obj>,
        pub rodata_data: Option<&'obj mut types::rodata>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> OpenTproxyMaps<'obj> {
        #[allow(unused_variables)]
        unsafe fn new(
            config: &libbpf_rs::__internal_skel::ObjectSkeletonConfig<'_>,
            object: &mut libbpf_rs::OpenObject,
        ) -> libbpf_rs::Result<Self> {
            let mut rodata = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::OpenObject, &'obj mut libbpf_rs::OpenObject>(
                    object,
                )
            };
            #[allow(clippy::never_loop)]
            for map in object.maps_mut() {
                let name = map.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "map has invalid name",
                    ))
                })?;
                #[allow(clippy::match_single_binding)]
                match name {
                    "tproxy_b.rodata" => rodata = Some(map),
                    _ => panic!("encountered unexpected map: `{name}`"),
                }
            }

            let slf = Self {
                rodata: rodata.expect("map `rodata` not present"),
                rodata_data: unsafe {
                    config
                        .map_mmap_ptr(0)
                        .expect("BPF map `rodata` does not have mmap pointer")
                        .cast::<types::rodata>()
                        .as_mut()
                },
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct TproxyMaps<'obj> {
        pub rodata: libbpf_rs::MapMut<'obj>,
        pub rodata_data: Option<&'obj types::rodata>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> TproxyMaps<'obj> {
        #[allow(unused_variables)]
        unsafe fn new(
            config: &libbpf_rs::__internal_skel::ObjectSkeletonConfig<'_>,
            object: &mut libbpf_rs::Object,
        ) -> libbpf_rs::Result<Self> {
            let mut rodata = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::Object, &'obj mut libbpf_rs::Object>(object)
            };
            #[allow(clippy::never_loop)]
            for map in object.maps_mut() {
                let name = map.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "map has invalid name",
                    ))
                })?;
                #[allow(clippy::match_single_binding)]
                match name {
                    "tproxy_b.rodata" => rodata = Some(map),
                    _ => panic!("encountered unexpected map: `{name}`"),
                }
            }

            let slf = Self {
                rodata: rodata.expect("map `rodata` not present"),
                rodata_data: unsafe {
                    config
                        .map_mmap_ptr(0)
                        .expect("BPF map `rodata` does not have mmap pointer")
                        .cast::<types::rodata>()
                        .as_ref()
                },
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct OpenTproxyProgs<'obj> {
        pub tproxy: libbpf_rs::OpenProgramMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> OpenTproxyProgs<'obj> {
        unsafe fn new(object: &mut libbpf_rs::OpenObject) -> libbpf_rs::Result<Self> {
            let mut tproxy = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::OpenObject, &'obj mut libbpf_rs::OpenObject>(
                    object,
                )
            };
            for prog in object.progs_mut() {
                let name = prog.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "prog has invalid name",
                    ))
                })?;
                match name {
                    "tproxy" => tproxy = Some(prog),
                    _ => panic!("encountered unexpected prog: `{name}`"),
                }
            }

            let slf = Self {
                tproxy: tproxy.expect("prog `tproxy` not present"),
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct TproxyProgs<'obj> {
        pub tproxy: libbpf_rs::ProgramMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> TproxyProgs<'obj> {
        #[allow(unused_variables)]
        fn new(open_progs: OpenTproxyProgs<'obj>) -> Self {
            Self {
                tproxy: unsafe {
                    libbpf_rs::ProgramMut::new_mut(open_progs.tproxy.as_libbpf_object().as_mut())
                },
                _phantom: std::marker::PhantomData,
            }
        }
    }
    struct OwnedRef<'obj, O> {
        object: Option<&'obj mut std::mem::MaybeUninit<O>>,
    }

    impl<'obj, O> OwnedRef<'obj, O> {
        /// # Safety
        /// The object has to be initialized.
        unsafe fn new(object: &'obj mut std::mem::MaybeUninit<O>) -> Self {
            Self {
                object: Some(object),
            }
        }

        fn as_ref(&self) -> &O {
            // SAFETY: As per the contract during construction, the
            //         object has to be initialized.
            unsafe { self.object.as_ref().unwrap().assume_init_ref() }
        }

        fn as_mut(&mut self) -> &mut O {
            // SAFETY: As per the contract during construction, the
            //         object has to be initialized.
            unsafe { self.object.as_mut().unwrap().assume_init_mut() }
        }

        fn take(mut self) -> &'obj mut std::mem::MaybeUninit<O> {
            self.object.take().unwrap()
        }
    }

    impl<O> Drop for OwnedRef<'_, O> {
        fn drop(&mut self) {
            if let Some(object) = &mut self.object {
                unsafe { object.assume_init_drop() }
            }
        }
    }

    #[derive(Default)]
    pub struct TproxySkelBuilder {
        pub obj_builder: libbpf_rs::ObjectBuilder,
    }

    impl<'obj> TproxySkelBuilder {
        fn open_opts_impl(
            self,
            open_opts: *const libbpf_sys::bpf_object_open_opts,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenTproxySkel<'obj>> {
            let skel_config = build_skel_config()?;
            let skel_ptr = skel_config.as_libbpf_object();

            let ret =
                unsafe { libbpf_sys::bpf_object__open_skeleton(skel_ptr.as_ptr(), open_opts) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            // SAFETY: `skel_ptr` points to a valid object after the
            //         open call.
            let obj_ptr = unsafe { *skel_ptr.as_ref().obj };
            // SANITY: `bpf_object__open_skeleton` should have
            //         allocated the object.
            let obj_ptr = std::ptr::NonNull::new(obj_ptr).unwrap();
            // SAFETY: `obj_ptr` points to an opened object after
            //         skeleton open.
            let obj = unsafe { libbpf_rs::OpenObject::from_ptr(obj_ptr) };
            let _obj = object.write(obj);
            // SAFETY: We just wrote initialized data to `object`.
            let mut obj_ref = unsafe { OwnedRef::new(object) };

            #[allow(unused_mut)]
            let mut skel = OpenTproxySkel {
                maps: unsafe { OpenTproxyMaps::new(&skel_config, obj_ref.as_mut())? },
                progs: unsafe { OpenTproxyProgs::new(obj_ref.as_mut())? },
                obj: obj_ref,
                // SAFETY: Our `struct_ops` type contains only pointers,
                //         which are allowed to be NULL.
                // TODO: Generate and use a `Default` representation
                //       instead, to cut down on unsafe code.
                struct_ops: unsafe { std::mem::zeroed() },
                skel_config,
            };

            Ok(skel)
        }
    }

    impl<'obj> SkelBuilder<'obj> for TproxySkelBuilder {
        type Output = OpenTproxySkel<'obj>;
        fn open(
            self,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenTproxySkel<'obj>> {
            self.open_opts_impl(std::ptr::null(), object)
        }

        fn open_opts(
            self,
            open_opts: libbpf_sys::bpf_object_open_opts,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenTproxySkel<'obj>> {
            self.open_opts_impl(&open_opts, object)
        }

        fn object_builder(&self) -> &libbpf_rs::ObjectBuilder {
            &self.obj_builder
        }
        fn object_builder_mut(&mut self) -> &mut libbpf_rs::ObjectBuilder {
            &mut self.obj_builder
        }
    }

    #[derive(Debug, Clone)]
    #[repr(C)]
    pub struct StructOps {}

    impl StructOps {}
    pub mod types {
        #[allow(unused_imports)]
        use super::*;
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct __sk_buff {
            pub len: u32,
            pub pkt_type: u32,
            pub mark: u32,
            pub queue_mapping: u32,
            pub protocol: u32,
            pub vlan_present: u32,
            pub vlan_tci: u32,
            pub vlan_proto: u32,
            pub priority: u32,
            pub ingress_ifindex: u32,
            pub ifindex: u32,
            pub tc_index: u32,
            pub cb: [u32; 5],
            pub hash: u32,
            pub tc_classid: u32,
            pub data: u32,
            pub data_end: u32,
            pub napi_id: u32,
            pub family: u32,
            pub remote_ip4: u32,
            pub local_ip4: u32,
            pub remote_ip6: [u32; 4],
            pub local_ip6: [u32; 4],
            pub remote_port: u32,
            pub local_port: u32,
            pub data_meta: u32,
            pub __anon___sk_buff_1: __anon___sk_buff_1,
            pub tstamp: u64,
            pub wire_len: u32,
            pub gso_segs: u32,
            pub __anon___sk_buff_2: __anon___sk_buff_2,
            pub gso_size: u32,
            pub tstamp_type: u8,
            pub hwtstamp: u64,
        }
        #[derive(Copy, Clone)]
        #[repr(C)]
        pub union __anon___sk_buff_1 {
            pub flow_keys: *mut std::ffi::c_void,
        }
        impl std::fmt::Debug for __anon___sk_buff_1 {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "(???)")
            }
        }
        impl Default for __anon___sk_buff_1 {
            fn default() -> Self {
                Self {
                    flow_keys: std::ptr::null_mut(),
                }
            }
        }
        #[derive(Copy, Clone)]
        #[repr(C)]
        pub union __anon___sk_buff_2 {
            pub sk: *mut bpf_sock,
        }
        impl std::fmt::Debug for __anon___sk_buff_2 {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "(???)")
            }
        }
        impl Default for __anon___sk_buff_2 {
            fn default() -> Self {
                Self {
                    sk: std::ptr::null_mut(),
                }
            }
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct bpf_sock {
            pub bound_dev_if: u32,
            pub family: u32,
            pub r#type: u32,
            pub protocol: u32,
            pub mark: u32,
            pub priority: u32,
            pub src_ip4: u32,
            pub src_ip6: [u32; 4],
            pub src_port: u32,
            pub dst_port: u16,
            pub dst_ip4: u32,
            pub dst_ip6: [u32; 4],
            pub state: u32,
            pub rx_queue_mapping: i32,
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct ethhdr {
            pub h_dest: [u8; 6],
            pub h_source: [u8; 6],
            pub h_proto: u16,
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct iphdr {
            pub __pad_0: [u8; 1],
            pub tos: u8,
            pub tot_len: u16,
            pub id: u16,
            pub frag_off: u16,
            pub ttl: u8,
            pub protocol: u8,
            pub check: u16,
            pub __anon_iphdr_1: __anon_iphdr_1,
        }
        #[derive(Copy, Clone)]
        #[repr(C)]
        pub union __anon_iphdr_1 {
            pub __anon_iphdr_2: __anon_iphdr_2,
            pub addrs: __anon_iphdr_2,
        }
        impl std::fmt::Debug for __anon_iphdr_1 {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "(???)")
            }
        }
        impl Default for __anon_iphdr_1 {
            fn default() -> Self {
                Self {
                    __anon_iphdr_2: __anon_iphdr_2::default(),
                }
            }
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_iphdr_2 {
            pub saddr: u32,
            pub daddr: u32,
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct bpf_sock_tuple {
            pub __anon_bpf_sock_tuple_1: __anon_bpf_sock_tuple_1,
        }
        #[derive(Copy, Clone)]
        #[repr(C)]
        pub union __anon_bpf_sock_tuple_1 {
            pub ipv4: __anon_bpf_sock_tuple_2,
            pub ipv6: __anon_bpf_sock_tuple_3,
        }
        impl std::fmt::Debug for __anon_bpf_sock_tuple_1 {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "(???)")
            }
        }
        impl Default for __anon_bpf_sock_tuple_1 {
            fn default() -> Self {
                Self {
                    ipv4: __anon_bpf_sock_tuple_2::default(),
                }
            }
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_bpf_sock_tuple_2 {
            pub saddr: u32,
            pub daddr: u32,
            pub sport: u16,
            pub dport: u16,
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_bpf_sock_tuple_3 {
            pub saddr: [u32; 4],
            pub daddr: [u32; 4],
            pub sport: u16,
            pub dport: u16,
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct rodata {
            pub target_port: u16,
            pub proxy_addr: u32,
            pub proxy_port: u16,
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct license {
            pub _license: [i8; 4],
        }
    }
    pub struct OpenTproxySkel<'obj> {
        obj: OwnedRef<'obj, libbpf_rs::OpenObject>,
        pub maps: OpenTproxyMaps<'obj>,
        pub progs: OpenTproxyProgs<'obj>,
        pub struct_ops: StructOps,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'obj>,
    }

    impl<'obj> OpenSkel<'obj> for OpenTproxySkel<'obj> {
        type Output = TproxySkel<'obj>;
        fn load(self) -> libbpf_rs::Result<TproxySkel<'obj>> {
            let skel_ptr = self.skel_config.as_libbpf_object().as_ptr();

            let ret = unsafe { libbpf_sys::bpf_object__load_skeleton(skel_ptr) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            let obj_ref = self.obj.take();
            let open_obj = std::mem::replace(obj_ref, std::mem::MaybeUninit::uninit());
            // SAFETY: `open_obj` is guaranteed to be properly
            //         initialized as it came from an `OwnedRef`.
            let obj_ptr = unsafe { open_obj.assume_init().take_ptr() };
            // SAFETY: `obj_ptr` points to a loaded object after
            //         skeleton load.
            let obj = unsafe { libbpf_rs::Object::from_ptr(obj_ptr) };
            // SAFETY: `OpenObject` and `Object` are guaranteed to
            //         have the same memory layout.
            let obj_ref = unsafe {
                std::mem::transmute::<
                    &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
                    &'obj mut std::mem::MaybeUninit<libbpf_rs::Object>,
                >(obj_ref)
            };
            let _obj = obj_ref.write(obj);
            // SAFETY: We just wrote initialized data to `obj_ref`.
            let mut obj_ref = unsafe { OwnedRef::new(obj_ref) };

            Ok(TproxySkel {
                maps: unsafe { TproxyMaps::new(&self.skel_config, obj_ref.as_mut())? },
                progs: TproxyProgs::new(self.progs),
                obj: obj_ref,
                struct_ops: self.struct_ops,
                skel_config: self.skel_config,
                links: TproxyLinks::default(),
            })
        }

        fn open_object(&self) -> &libbpf_rs::OpenObject {
            self.obj.as_ref()
        }

        fn open_object_mut(&mut self) -> &mut libbpf_rs::OpenObject {
            self.obj.as_mut()
        }
    }
    #[derive(Default)]
    pub struct TproxyLinks {
        pub tproxy: Option<libbpf_rs::Link>,
    }
    pub struct TproxySkel<'obj> {
        obj: OwnedRef<'obj, libbpf_rs::Object>,
        pub maps: TproxyMaps<'obj>,
        pub progs: TproxyProgs<'obj>,
        struct_ops: StructOps,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'obj>,
        pub links: TproxyLinks,
    }

    unsafe impl Send for TproxySkel<'_> {}
    unsafe impl Sync for TproxySkel<'_> {}

    impl<'obj> Skel<'obj> for TproxySkel<'obj> {
        fn object(&self) -> &libbpf_rs::Object {
            self.obj.as_ref()
        }

        fn object_mut(&mut self) -> &mut libbpf_rs::Object {
            self.obj.as_mut()
        }
        fn attach(&mut self) -> libbpf_rs::Result<()> {
            let skel_ptr = self.skel_config.as_libbpf_object().as_ptr();
            let ret = unsafe { libbpf_sys::bpf_object__attach_skeleton(skel_ptr) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            self.links = TproxyLinks {
                tproxy: core::ptr::NonNull::new(self.skel_config.prog_link_ptr(0)?)
                    .map(|ptr| unsafe { libbpf_rs::Link::from_ptr(ptr) }),
            };

            Ok(())
        }
    }
    impl TproxySkel<'_> {
        pub fn struct_ops_raw(&self) -> *const StructOps {
            &self.struct_ops
        }

        pub fn struct_ops(&self) -> &StructOps {
            &self.struct_ops
        }
    }
    const DATA: &[u8] = &[
        127, 69, 76, 70, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 247, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 96, 24, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0,
        0, 64, 0, 9, 0, 1, 0, 0, 46, 115, 116, 114, 116, 97, 98, 0, 46, 115, 121, 109, 116, 97, 98,
        0, 116, 99, 0, 46, 114, 111, 100, 97, 116, 97, 0, 108, 105, 99, 101, 110, 115, 101, 0, 116,
        112, 114, 111, 120, 121, 46, 98, 112, 102, 46, 99, 0, 104, 97, 110, 100, 108, 101, 95, 116,
        99, 112, 46, 95, 95, 95, 102, 109, 116, 0, 116, 112, 114, 111, 120, 121, 0, 116, 97, 114,
        103, 101, 116, 95, 112, 111, 114, 116, 0, 112, 114, 111, 120, 121, 95, 97, 100, 100, 114,
        0, 112, 114, 111, 120, 121, 95, 112, 111, 114, 116, 0, 95, 108, 105, 99, 101, 110, 115,
        101, 0, 46, 114, 101, 108, 116, 99, 0, 46, 66, 84, 70, 0, 46, 66, 84, 70, 46, 101, 120,
        116, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 36, 0, 0, 0, 4, 0, 241, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 3, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 49, 0, 0, 0, 1, 0, 4, 0, 10,
        0, 0, 0, 0, 0, 0, 0, 31, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 67, 0, 0, 0, 18, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 112, 3, 0, 0,
        0, 0, 0, 0, 74, 0, 0, 0, 17, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 86,
        0, 0, 0, 17, 0, 4, 0, 4, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 97, 0, 0, 0, 17, 0,
        4, 0, 8, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 108, 0, 0, 0, 17, 0, 5, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 180, 0, 0, 0, 2, 0, 0, 0, 97, 18, 80, 0, 0, 0, 0, 0,
        97, 19, 76, 0, 0, 0, 0, 0, 191, 54, 0, 0, 0, 0, 0, 0, 7, 6, 0, 0, 14, 0, 0, 0, 45, 38, 103,
        0, 0, 0, 0, 0, 105, 52, 12, 0, 0, 0, 0, 0, 86, 4, 101, 0, 8, 0, 0, 0, 7, 3, 0, 0, 34, 0, 0,
        0, 45, 35, 99, 0, 0, 0, 0, 0, 113, 98, 0, 0, 0, 0, 0, 0, 84, 2, 0, 0, 15, 0, 0, 0, 86, 2,
        96, 0, 5, 0, 0, 0, 113, 98, 9, 0, 0, 0, 0, 0, 86, 2, 94, 0, 6, 0, 0, 0, 183, 2, 0, 0, 12,
        0, 0, 0, 15, 38, 0, 0, 0, 0, 0, 0, 21, 6, 91, 0, 0, 0, 0, 0, 180, 2, 0, 0, 0, 0, 0, 0, 99,
        42, 248, 255, 0, 0, 0, 0, 183, 2, 0, 0, 0, 0, 0, 0, 123, 42, 240, 255, 0, 0, 0, 0, 123, 42,
        232, 255, 0, 0, 0, 0, 123, 42, 224, 255, 0, 0, 0, 0, 123, 42, 216, 255, 0, 0, 0, 0, 191,
        98, 0, 0, 0, 0, 0, 0, 7, 2, 0, 0, 12, 0, 0, 0, 97, 19, 80, 0, 0, 0, 0, 0, 45, 50, 80, 0, 0,
        0, 0, 0, 105, 98, 10, 0, 0, 0, 0, 0, 24, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 105,
        51, 0, 0, 0, 0, 0, 0, 30, 50, 1, 0, 0, 0, 0, 0, 5, 0, 73, 0, 0, 0, 0, 0, 191, 24, 0, 0, 0,
        0, 0, 0, 191, 98, 0, 0, 0, 0, 0, 0, 180, 3, 0, 0, 12, 0, 0, 0, 183, 4, 0, 0, 255, 255, 255,
        255, 183, 5, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 99, 0, 0, 0, 191, 7, 0, 0, 0, 0, 0, 0, 21, 7,
        5, 0, 0, 0, 0, 0, 97, 114, 72, 0, 0, 0, 0, 0, 191, 129, 0, 0, 0, 0, 0, 0, 86, 2, 54, 0, 10,
        0, 0, 0, 191, 113, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 86, 0, 0, 0, 183, 1, 0, 0, 0, 0, 0, 0,
        191, 167, 0, 0, 0, 0, 0, 0, 7, 7, 0, 0, 216, 255, 255, 255, 191, 114, 0, 0, 0, 0, 0, 0, 15,
        18, 0, 0, 0, 0, 0, 0, 97, 97, 0, 0, 0, 0, 0, 0, 99, 23, 0, 0, 0, 0, 0, 0, 183, 1, 0, 0, 4,
        0, 0, 0, 24, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 97, 51, 0, 0, 0, 0, 0, 0, 99, 55,
        4, 0, 0, 0, 0, 0, 105, 99, 8, 0, 0, 0, 0, 0, 107, 55, 8, 0, 0, 0, 0, 0, 24, 3, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 105, 51, 0, 0, 0, 0, 0, 0, 107, 55, 10, 0, 0, 0, 0, 0, 123,
        42, 184, 255, 0, 0, 0, 0, 105, 114, 8, 0, 0, 0, 0, 0, 220, 2, 0, 0, 16, 0, 0, 0, 123, 42,
        192, 255, 0, 0, 0, 0, 191, 114, 0, 0, 0, 0, 0, 0, 15, 18, 0, 0, 0, 0, 0, 0, 123, 42, 200,
        255, 0, 0, 0, 0, 105, 113, 10, 0, 0, 0, 0, 0, 220, 1, 0, 0, 16, 0, 0, 0, 123, 26, 208, 255,
        0, 0, 0, 0, 191, 163, 0, 0, 0, 0, 0, 0, 7, 3, 0, 0, 184, 255, 255, 255, 24, 1, 0, 0, 10, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 180, 2, 0, 0, 31, 0, 0, 0, 180, 4, 0, 0, 32, 0, 0, 0, 133, 0,
        0, 0, 177, 0, 0, 0, 191, 134, 0, 0, 0, 0, 0, 0, 191, 97, 0, 0, 0, 0, 0, 0, 191, 114, 0, 0,
        0, 0, 0, 0, 180, 3, 0, 0, 12, 0, 0, 0, 183, 4, 0, 0, 255, 255, 255, 255, 183, 5, 0, 0, 0,
        0, 0, 0, 133, 0, 0, 0, 99, 0, 0, 0, 191, 97, 0, 0, 0, 0, 0, 0, 191, 7, 0, 0, 0, 0, 0, 0,
        180, 0, 0, 0, 2, 0, 0, 0, 21, 7, 15, 0, 0, 0, 0, 0, 97, 114, 72, 0, 0, 0, 0, 0, 22, 2, 4,
        0, 10, 0, 0, 0, 191, 113, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 86, 0, 0, 0, 180, 0, 0, 0, 2, 0,
        0, 0, 5, 0, 9, 0, 0, 0, 0, 0, 191, 114, 0, 0, 0, 0, 0, 0, 183, 3, 0, 0, 0, 0, 0, 0, 133, 0,
        0, 0, 124, 0, 0, 0, 191, 6, 0, 0, 0, 0, 0, 0, 191, 113, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 86,
        0, 0, 0, 180, 0, 0, 0, 2, 0, 0, 0, 86, 6, 1, 0, 0, 0, 0, 0, 180, 0, 0, 0, 0, 0, 0, 0, 149,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 108, 111, 111, 107, 117, 112, 32, 116,
        99, 112, 32, 32, 37, 112, 73, 52, 58, 37, 100, 32, 45, 62, 32, 37, 112, 73, 52, 58, 37,
        100, 0, 71, 80, 76, 0, 0, 0, 0, 240, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 6, 0, 0, 0, 192, 1,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 7, 0, 0, 0, 240, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 8, 0, 0, 0,
        112, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 4, 0, 0, 0, 159, 235, 1, 0, 24, 0, 0, 0, 0, 0, 0, 0,
        200, 6, 0, 0, 200, 6, 0, 0, 204, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 1, 0, 0, 0,
        34, 0, 0, 4, 192, 0, 0, 0, 11, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 15, 0, 0, 0, 3, 0, 0, 0,
        32, 0, 0, 0, 24, 0, 0, 0, 3, 0, 0, 0, 64, 0, 0, 0, 29, 0, 0, 0, 3, 0, 0, 0, 96, 0, 0, 0,
        43, 0, 0, 0, 3, 0, 0, 0, 128, 0, 0, 0, 52, 0, 0, 0, 3, 0, 0, 0, 160, 0, 0, 0, 65, 0, 0, 0,
        3, 0, 0, 0, 192, 0, 0, 0, 74, 0, 0, 0, 3, 0, 0, 0, 224, 0, 0, 0, 85, 0, 0, 0, 3, 0, 0, 0,
        0, 1, 0, 0, 94, 0, 0, 0, 3, 0, 0, 0, 32, 1, 0, 0, 110, 0, 0, 0, 3, 0, 0, 0, 64, 1, 0, 0,
        118, 0, 0, 0, 3, 0, 0, 0, 96, 1, 0, 0, 127, 0, 0, 0, 5, 0, 0, 0, 128, 1, 0, 0, 130, 0, 0,
        0, 3, 0, 0, 0, 32, 2, 0, 0, 135, 0, 0, 0, 3, 0, 0, 0, 64, 2, 0, 0, 146, 0, 0, 0, 3, 0, 0,
        0, 96, 2, 0, 0, 151, 0, 0, 0, 3, 0, 0, 0, 128, 2, 0, 0, 160, 0, 0, 0, 3, 0, 0, 0, 160, 2,
        0, 0, 168, 0, 0, 0, 3, 0, 0, 0, 192, 2, 0, 0, 175, 0, 0, 0, 3, 0, 0, 0, 224, 2, 0, 0, 186,
        0, 0, 0, 3, 0, 0, 0, 0, 3, 0, 0, 196, 0, 0, 0, 7, 0, 0, 0, 32, 3, 0, 0, 207, 0, 0, 0, 7, 0,
        0, 0, 160, 3, 0, 0, 217, 0, 0, 0, 3, 0, 0, 0, 32, 4, 0, 0, 229, 0, 0, 0, 3, 0, 0, 0, 64, 4,
        0, 0, 240, 0, 0, 0, 3, 0, 0, 0, 96, 4, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 128, 4, 0, 0, 250, 0,
        0, 0, 10, 0, 0, 0, 192, 4, 0, 0, 1, 1, 0, 0, 3, 0, 0, 0, 0, 5, 0, 0, 10, 1, 0, 0, 3, 0, 0,
        0, 32, 5, 0, 0, 0, 0, 0, 0, 12, 0, 0, 0, 64, 5, 0, 0, 19, 1, 0, 0, 3, 0, 0, 0, 128, 5, 0,
        0, 28, 1, 0, 0, 14, 0, 0, 0, 160, 5, 0, 0, 40, 1, 0, 0, 10, 0, 0, 0, 192, 5, 0, 0, 49, 1,
        0, 0, 0, 0, 0, 8, 4, 0, 0, 0, 55, 1, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 3, 0, 0, 0, 0, 3, 0, 0, 0, 6, 0, 0, 0, 5, 0, 0, 0, 68, 1, 0, 0, 0, 0, 0, 1, 4, 0,
        0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 3, 0, 0, 0, 6, 0, 0, 0, 4, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 5, 8, 0, 0, 0, 88, 1, 0, 0, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 2, 49, 0, 0, 0, 98, 1, 0, 0, 0, 0, 0, 8, 11, 0, 0, 0, 104, 1, 0, 0, 0, 0, 0, 1, 8, 0, 0,
        0, 64, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 5, 8, 0, 0, 0, 123, 1, 0, 0, 13, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 2, 34, 0, 0, 0, 126, 1, 0, 0, 0, 0, 0, 8, 15, 0, 0, 0, 131, 1, 0, 0,
        0, 0, 0, 1, 1, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 13, 17, 0, 0, 0, 145, 1, 0, 0, 1,
        0, 0, 0, 149, 1, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0, 32, 0, 0, 1, 153, 1, 0, 0, 1, 0, 0, 12, 16,
        0, 0, 0, 160, 1, 0, 0, 3, 0, 0, 4, 14, 0, 0, 0, 167, 1, 0, 0, 20, 0, 0, 0, 0, 0, 0, 0, 174,
        1, 0, 0, 20, 0, 0, 0, 48, 0, 0, 0, 183, 1, 0, 0, 21, 0, 0, 0, 96, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 3, 0, 0, 0, 0, 15, 0, 0, 0, 6, 0, 0, 0, 6, 0, 0, 0, 191, 1, 0, 0, 0, 0, 0, 8, 22, 0,
        0, 0, 198, 1, 0, 0, 0, 0, 0, 8, 23, 0, 0, 0, 204, 1, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 16, 0,
        0, 0, 219, 1, 0, 0, 10, 0, 0, 132, 20, 0, 0, 0, 225, 1, 0, 0, 14, 0, 0, 0, 0, 0, 0, 4, 229,
        1, 0, 0, 14, 0, 0, 0, 4, 0, 0, 4, 237, 1, 0, 0, 14, 0, 0, 0, 8, 0, 0, 0, 241, 1, 0, 0, 21,
        0, 0, 0, 16, 0, 0, 0, 249, 1, 0, 0, 21, 0, 0, 0, 32, 0, 0, 0, 252, 1, 0, 0, 21, 0, 0, 0,
        48, 0, 0, 0, 5, 2, 0, 0, 14, 0, 0, 0, 64, 0, 0, 0, 43, 0, 0, 0, 14, 0, 0, 0, 72, 0, 0, 0,
        9, 2, 0, 0, 25, 0, 0, 0, 80, 0, 0, 0, 0, 0, 0, 0, 26, 0, 0, 0, 96, 0, 0, 0, 15, 2, 0, 0, 0,
        0, 0, 8, 22, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 5, 8, 0, 0, 0, 0, 0, 0, 0, 27, 0, 0, 0, 0, 0, 0,
        0, 23, 2, 0, 0, 27, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 4, 8, 0, 0, 0, 29, 2, 0, 0,
        28, 0, 0, 0, 0, 0, 0, 0, 35, 2, 0, 0, 28, 0, 0, 0, 32, 0, 0, 0, 41, 2, 0, 0, 0, 0, 0, 8, 3,
        0, 0, 0, 48, 2, 0, 0, 1, 0, 0, 4, 36, 0, 0, 0, 0, 0, 0, 0, 30, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 2, 0, 0, 5, 36, 0, 0, 0, 63, 2, 0, 0, 31, 0, 0, 0, 0, 0, 0, 0, 68, 2, 0, 0, 32, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 4, 12, 0, 0, 0, 29, 2, 0, 0, 28, 0, 0, 0, 0, 0, 0, 0,
        35, 2, 0, 0, 28, 0, 0, 0, 32, 0, 0, 0, 73, 2, 0, 0, 21, 0, 0, 0, 64, 0, 0, 0, 79, 2, 0, 0,
        21, 0, 0, 0, 80, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 4, 36, 0, 0, 0, 29, 2, 0, 0, 33, 0, 0, 0, 0,
        0, 0, 0, 35, 2, 0, 0, 33, 0, 0, 0, 128, 0, 0, 0, 73, 2, 0, 0, 21, 0, 0, 0, 0, 1, 0, 0, 79,
        2, 0, 0, 21, 0, 0, 0, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 28, 0, 0, 0, 6, 0,
        0, 0, 4, 0, 0, 0, 85, 2, 0, 0, 14, 0, 0, 4, 80, 0, 0, 0, 94, 2, 0, 0, 3, 0, 0, 0, 0, 0, 0,
        0, 168, 0, 0, 0, 3, 0, 0, 0, 32, 0, 0, 0, 107, 2, 0, 0, 3, 0, 0, 0, 64, 0, 0, 0, 43, 0, 0,
        0, 3, 0, 0, 0, 96, 0, 0, 0, 24, 0, 0, 0, 3, 0, 0, 0, 128, 0, 0, 0, 85, 0, 0, 0, 3, 0, 0, 0,
        160, 0, 0, 0, 112, 2, 0, 0, 3, 0, 0, 0, 192, 0, 0, 0, 120, 2, 0, 0, 7, 0, 0, 0, 224, 0, 0,
        0, 128, 2, 0, 0, 3, 0, 0, 0, 96, 1, 0, 0, 137, 2, 0, 0, 21, 0, 0, 0, 128, 1, 0, 0, 146, 2,
        0, 0, 3, 0, 0, 0, 160, 1, 0, 0, 154, 2, 0, 0, 7, 0, 0, 0, 192, 1, 0, 0, 162, 2, 0, 0, 3, 0,
        0, 0, 64, 2, 0, 0, 168, 2, 0, 0, 35, 0, 0, 0, 96, 2, 0, 0, 185, 2, 0, 0, 0, 0, 0, 8, 17, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 37, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 21, 0, 0, 0, 191, 2, 0,
        0, 0, 0, 0, 14, 36, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 40, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 9, 28, 0, 0, 0, 203, 2, 0, 0, 0, 0, 0, 14, 39, 0, 0, 0, 1, 0, 0, 0, 214, 2, 0, 0,
        0, 0, 0, 14, 36, 0, 0, 0, 1, 0, 0, 0, 225, 2, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 8, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 43, 0, 0, 0, 6, 0, 0, 0, 4, 0, 0, 0, 230, 2, 0, 0, 0, 0,
        0, 14, 44, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 43, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        3, 0, 0, 0, 0, 46, 0, 0, 0, 6, 0, 0, 0, 31, 0, 0, 0, 239, 2, 0, 0, 0, 0, 0, 14, 47, 0, 0,
        0, 0, 0, 0, 0, 1, 3, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 185, 7, 0, 0, 4, 0, 0, 15, 41, 0, 0, 0,
        38, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 41, 0, 0, 0, 4, 0, 0, 0, 4, 0, 0, 0, 42, 0, 0, 0, 8,
        0, 0, 0, 2, 0, 0, 0, 48, 0, 0, 0, 10, 0, 0, 0, 31, 0, 0, 0, 193, 7, 0, 0, 1, 0, 0, 15, 4,
        0, 0, 0, 45, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 95, 95, 115, 107, 95, 98, 117, 102, 102,
        0, 108, 101, 110, 0, 112, 107, 116, 95, 116, 121, 112, 101, 0, 109, 97, 114, 107, 0, 113,
        117, 101, 117, 101, 95, 109, 97, 112, 112, 105, 110, 103, 0, 112, 114, 111, 116, 111, 99,
        111, 108, 0, 118, 108, 97, 110, 95, 112, 114, 101, 115, 101, 110, 116, 0, 118, 108, 97,
        110, 95, 116, 99, 105, 0, 118, 108, 97, 110, 95, 112, 114, 111, 116, 111, 0, 112, 114, 105,
        111, 114, 105, 116, 121, 0, 105, 110, 103, 114, 101, 115, 115, 95, 105, 102, 105, 110, 100,
        101, 120, 0, 105, 102, 105, 110, 100, 101, 120, 0, 116, 99, 95, 105, 110, 100, 101, 120, 0,
        99, 98, 0, 104, 97, 115, 104, 0, 116, 99, 95, 99, 108, 97, 115, 115, 105, 100, 0, 100, 97,
        116, 97, 0, 100, 97, 116, 97, 95, 101, 110, 100, 0, 110, 97, 112, 105, 95, 105, 100, 0,
        102, 97, 109, 105, 108, 121, 0, 114, 101, 109, 111, 116, 101, 95, 105, 112, 52, 0, 108,
        111, 99, 97, 108, 95, 105, 112, 52, 0, 114, 101, 109, 111, 116, 101, 95, 105, 112, 54, 0,
        108, 111, 99, 97, 108, 95, 105, 112, 54, 0, 114, 101, 109, 111, 116, 101, 95, 112, 111,
        114, 116, 0, 108, 111, 99, 97, 108, 95, 112, 111, 114, 116, 0, 100, 97, 116, 97, 95, 109,
        101, 116, 97, 0, 116, 115, 116, 97, 109, 112, 0, 119, 105, 114, 101, 95, 108, 101, 110, 0,
        103, 115, 111, 95, 115, 101, 103, 115, 0, 103, 115, 111, 95, 115, 105, 122, 101, 0, 116,
        115, 116, 97, 109, 112, 95, 116, 121, 112, 101, 0, 104, 119, 116, 115, 116, 97, 109, 112,
        0, 95, 95, 117, 51, 50, 0, 117, 110, 115, 105, 103, 110, 101, 100, 32, 105, 110, 116, 0,
        95, 95, 65, 82, 82, 65, 89, 95, 83, 73, 90, 69, 95, 84, 89, 80, 69, 95, 95, 0, 102, 108,
        111, 119, 95, 107, 101, 121, 115, 0, 95, 95, 117, 54, 52, 0, 117, 110, 115, 105, 103, 110,
        101, 100, 32, 108, 111, 110, 103, 32, 108, 111, 110, 103, 0, 115, 107, 0, 95, 95, 117, 56,
        0, 117, 110, 115, 105, 103, 110, 101, 100, 32, 99, 104, 97, 114, 0, 115, 107, 98, 0, 105,
        110, 116, 0, 116, 112, 114, 111, 120, 121, 0, 101, 116, 104, 104, 100, 114, 0, 104, 95,
        100, 101, 115, 116, 0, 104, 95, 115, 111, 117, 114, 99, 101, 0, 104, 95, 112, 114, 111,
        116, 111, 0, 95, 95, 98, 101, 49, 54, 0, 95, 95, 117, 49, 54, 0, 117, 110, 115, 105, 103,
        110, 101, 100, 32, 115, 104, 111, 114, 116, 0, 105, 112, 104, 100, 114, 0, 105, 104, 108,
        0, 118, 101, 114, 115, 105, 111, 110, 0, 116, 111, 115, 0, 116, 111, 116, 95, 108, 101,
        110, 0, 105, 100, 0, 102, 114, 97, 103, 95, 111, 102, 102, 0, 116, 116, 108, 0, 99, 104,
        101, 99, 107, 0, 95, 95, 115, 117, 109, 49, 54, 0, 97, 100, 100, 114, 115, 0, 115, 97, 100,
        100, 114, 0, 100, 97, 100, 100, 114, 0, 95, 95, 98, 101, 51, 50, 0, 98, 112, 102, 95, 115,
        111, 99, 107, 95, 116, 117, 112, 108, 101, 0, 105, 112, 118, 52, 0, 105, 112, 118, 54, 0,
        115, 112, 111, 114, 116, 0, 100, 112, 111, 114, 116, 0, 98, 112, 102, 95, 115, 111, 99,
        107, 0, 98, 111, 117, 110, 100, 95, 100, 101, 118, 95, 105, 102, 0, 116, 121, 112, 101, 0,
        115, 114, 99, 95, 105, 112, 52, 0, 115, 114, 99, 95, 105, 112, 54, 0, 115, 114, 99, 95,
        112, 111, 114, 116, 0, 100, 115, 116, 95, 112, 111, 114, 116, 0, 100, 115, 116, 95, 105,
        112, 52, 0, 100, 115, 116, 95, 105, 112, 54, 0, 115, 116, 97, 116, 101, 0, 114, 120, 95,
        113, 117, 101, 117, 101, 95, 109, 97, 112, 112, 105, 110, 103, 0, 95, 95, 115, 51, 50, 0,
        116, 97, 114, 103, 101, 116, 95, 112, 111, 114, 116, 0, 112, 114, 111, 120, 121, 95, 97,
        100, 100, 114, 0, 112, 114, 111, 120, 121, 95, 112, 111, 114, 116, 0, 99, 104, 97, 114, 0,
        95, 108, 105, 99, 101, 110, 115, 101, 0, 104, 97, 110, 100, 108, 101, 95, 116, 99, 112, 46,
        95, 95, 95, 102, 109, 116, 0, 98, 112, 102, 95, 102, 108, 111, 119, 95, 107, 101, 121, 115,
        0, 47, 114, 111, 111, 116, 47, 100, 111, 99, 107, 101, 114, 45, 112, 114, 111, 120, 121,
        47, 116, 112, 114, 111, 120, 121, 47, 115, 114, 99, 47, 98, 112, 102, 47, 116, 112, 114,
        111, 120, 121, 46, 98, 112, 102, 46, 99, 0, 105, 110, 116, 32, 116, 112, 114, 111, 120,
        121, 40, 115, 116, 114, 117, 99, 116, 32, 95, 95, 115, 107, 95, 98, 117, 102, 102, 32, 42,
        115, 107, 98, 41, 0, 32, 32, 32, 32, 118, 111, 105, 100, 32, 42, 100, 97, 116, 97, 95, 101,
        110, 100, 32, 61, 32, 40, 118, 111, 105, 100, 32, 42, 41, 40, 108, 111, 110, 103, 41, 115,
        107, 98, 45, 62, 100, 97, 116, 97, 95, 101, 110, 100, 59, 0, 32, 32, 32, 32, 118, 111, 105,
        100, 32, 42, 100, 97, 116, 97, 32, 61, 32, 40, 118, 111, 105, 100, 32, 42, 41, 40, 108,
        111, 110, 103, 41, 115, 107, 98, 45, 62, 100, 97, 116, 97, 59, 0, 32, 32, 32, 32, 105, 102,
        32, 40, 101, 116, 104, 32, 43, 32, 49, 32, 62, 32, 100, 97, 116, 97, 95, 101, 110, 100, 41,
        0, 32, 32, 32, 32, 105, 102, 32, 40, 101, 116, 104, 45, 62, 104, 95, 112, 114, 111, 116,
        111, 32, 33, 61, 32, 98, 112, 102, 95, 104, 116, 111, 110, 115, 40, 69, 84, 72, 95, 80, 95,
        73, 80, 41, 41, 0, 32, 32, 32, 32, 105, 102, 32, 40, 105, 112, 104, 45, 62, 105, 104, 108,
        32, 33, 61, 32, 53, 41, 0, 32, 32, 32, 32, 112, 114, 111, 116, 111, 32, 61, 32, 105, 112,
        104, 45, 62, 112, 114, 111, 116, 111, 99, 111, 108, 59, 0, 32, 32, 32, 32, 32, 32, 32, 32,
        115, 116, 114, 117, 99, 116, 32, 98, 112, 102, 95, 115, 111, 99, 107, 95, 116, 117, 112,
        108, 101, 32, 115, 101, 114, 118, 101, 114, 32, 61, 32, 123, 125, 59, 0, 32, 32, 32, 32,
        105, 102, 32, 40, 40, 118, 111, 105, 100, 32, 42, 41, 116, 117, 112, 108, 101, 32, 43, 32,
        116, 117, 112, 108, 101, 95, 108, 101, 110, 32, 62, 32, 40, 118, 111, 105, 100, 32, 42, 41,
        40, 108, 111, 110, 103, 41, 115, 107, 98, 45, 62, 100, 97, 116, 97, 95, 101, 110, 100, 41,
        0, 32, 32, 32, 32, 105, 102, 32, 40, 116, 117, 112, 108, 101, 45, 62, 105, 112, 118, 52,
        46, 100, 112, 111, 114, 116, 32, 33, 61, 32, 116, 97, 114, 103, 101, 116, 95, 112, 111,
        114, 116, 41, 0, 32, 32, 32, 32, 114, 101, 116, 117, 114, 110, 32, 114, 101, 116, 32, 61,
        61, 32, 48, 32, 63, 32, 84, 67, 95, 65, 67, 84, 95, 79, 75, 32, 58, 32, 84, 67, 95, 65, 67,
        84, 95, 83, 72, 79, 84, 59, 0, 32, 32, 32, 32, 115, 107, 32, 61, 32, 98, 112, 102, 95, 115,
        107, 99, 95, 108, 111, 111, 107, 117, 112, 95, 116, 99, 112, 40, 115, 107, 98, 44, 32, 116,
        117, 112, 108, 101, 44, 32, 116, 117, 112, 108, 101, 95, 108, 101, 110, 44, 32, 66, 80, 70,
        95, 70, 95, 67, 85, 82, 82, 69, 78, 84, 95, 78, 69, 84, 78, 83, 44, 32, 48, 41, 59, 0, 32,
        32, 32, 32, 105, 102, 32, 40, 115, 107, 41, 32, 123, 0, 32, 32, 32, 32, 32, 32, 32, 32,
        105, 102, 32, 40, 115, 107, 45, 62, 115, 116, 97, 116, 101, 32, 33, 61, 32, 66, 80, 70, 95,
        84, 67, 80, 95, 76, 73, 83, 84, 69, 78, 41, 0, 32, 32, 32, 32, 32, 32, 32, 32, 98, 112,
        102, 95, 115, 107, 95, 114, 101, 108, 101, 97, 115, 101, 40, 115, 107, 41, 59, 0, 32, 32,
        32, 32, 115, 101, 114, 118, 101, 114, 46, 105, 112, 118, 52, 46, 115, 97, 100, 100, 114,
        32, 61, 32, 116, 117, 112, 108, 101, 45, 62, 105, 112, 118, 52, 46, 115, 97, 100, 100, 114,
        59, 0, 32, 32, 32, 32, 115, 101, 114, 118, 101, 114, 46, 105, 112, 118, 52, 46, 100, 97,
        100, 100, 114, 32, 61, 32, 112, 114, 111, 120, 121, 95, 97, 100, 100, 114, 59, 0, 32, 32,
        32, 32, 115, 101, 114, 118, 101, 114, 46, 105, 112, 118, 52, 46, 115, 112, 111, 114, 116,
        32, 61, 32, 116, 117, 112, 108, 101, 45, 62, 105, 112, 118, 52, 46, 115, 112, 111, 114,
        116, 59, 0, 32, 32, 32, 32, 115, 101, 114, 118, 101, 114, 46, 105, 112, 118, 52, 46, 100,
        112, 111, 114, 116, 32, 61, 32, 112, 114, 111, 120, 121, 95, 112, 111, 114, 116, 59, 0, 32,
        32, 32, 32, 98, 112, 102, 95, 112, 114, 105, 110, 116, 107, 40, 34, 108, 111, 111, 107,
        117, 112, 32, 116, 99, 112, 32, 32, 37, 112, 73, 52, 58, 37, 100, 32, 45, 62, 32, 37, 112,
        73, 52, 58, 37, 100, 34, 44, 32, 38, 115, 101, 114, 118, 101, 114, 46, 105, 112, 118, 52,
        46, 115, 97, 100, 100, 114, 44, 98, 112, 102, 95, 110, 116, 111, 104, 115, 40, 32, 115,
        101, 114, 118, 101, 114, 46, 105, 112, 118, 52, 46, 115, 112, 111, 114, 116, 41, 44, 38,
        115, 101, 114, 118, 101, 114, 46, 105, 112, 118, 52, 46, 100, 97, 100, 100, 114, 44, 98,
        112, 102, 95, 110, 116, 111, 104, 115, 40, 115, 101, 114, 118, 101, 114, 46, 105, 112, 118,
        52, 46, 100, 112, 111, 114, 116, 41, 41, 59, 0, 32, 32, 32, 32, 115, 107, 32, 61, 32, 98,
        112, 102, 95, 115, 107, 99, 95, 108, 111, 111, 107, 117, 112, 95, 116, 99, 112, 40, 115,
        107, 98, 44, 32, 38, 115, 101, 114, 118, 101, 114, 44, 32, 116, 117, 112, 108, 101, 95,
        108, 101, 110, 44, 32, 66, 80, 70, 95, 70, 95, 67, 85, 82, 82, 69, 78, 84, 95, 78, 69, 84,
        78, 83, 44, 32, 48, 41, 59, 0, 32, 32, 32, 32, 105, 102, 32, 40, 33, 115, 107, 41, 0, 32,
        32, 32, 32, 105, 102, 32, 40, 115, 107, 45, 62, 115, 116, 97, 116, 101, 32, 33, 61, 32, 66,
        80, 70, 95, 84, 67, 80, 95, 76, 73, 83, 84, 69, 78, 41, 32, 123, 0, 32, 32, 32, 32, 114,
        101, 116, 32, 61, 32, 98, 112, 102, 95, 115, 107, 95, 97, 115, 115, 105, 103, 110, 40, 115,
        107, 98, 44, 32, 115, 107, 44, 32, 48, 41, 59, 0, 125, 0, 48, 58, 49, 54, 0, 48, 58, 49,
        53, 0, 48, 58, 50, 0, 48, 58, 48, 0, 48, 58, 55, 0, 48, 58, 57, 58, 48, 58, 48, 0, 48, 58,
        48, 58, 48, 58, 51, 0, 48, 58, 49, 50, 0, 48, 58, 48, 58, 48, 58, 48, 0, 48, 58, 48, 58,
        48, 58, 49, 0, 48, 58, 48, 58, 48, 58, 50, 0, 46, 114, 111, 100, 97, 116, 97, 0, 108, 105,
        99, 101, 110, 115, 101, 0, 116, 99, 0, 0, 0, 0, 0, 159, 235, 1, 0, 32, 0, 0, 0, 0, 0, 0, 0,
        20, 0, 0, 0, 20, 0, 0, 0, 140, 2, 0, 0, 160, 2, 0, 0, 76, 1, 0, 0, 8, 0, 0, 0, 201, 7, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 18, 0, 0, 0, 16, 0, 0, 0, 201, 7, 0, 0, 40, 0, 0, 0, 0, 0, 0, 0,
        15, 3, 0, 0, 62, 3, 0, 0, 0, 132, 1, 0, 8, 0, 0, 0, 15, 3, 0, 0, 96, 3, 0, 0, 41, 72, 0, 0,
        16, 0, 0, 0, 15, 3, 0, 0, 146, 3, 0, 0, 37, 76, 0, 0, 24, 0, 0, 0, 15, 3, 0, 0, 188, 3, 0,
        0, 13, 108, 0, 0, 40, 0, 0, 0, 15, 3, 0, 0, 188, 3, 0, 0, 17, 108, 0, 0, 48, 0, 0, 0, 15,
        3, 0, 0, 216, 3, 0, 0, 14, 124, 0, 0, 56, 0, 0, 0, 15, 3, 0, 0, 216, 3, 0, 0, 22, 124, 0,
        0, 80, 0, 0, 0, 15, 3, 0, 0, 5, 4, 0, 0, 14, 148, 0, 0, 96, 0, 0, 0, 15, 3, 0, 0, 5, 4, 0,
        0, 18, 148, 0, 0, 104, 0, 0, 0, 15, 3, 0, 0, 28, 4, 0, 0, 18, 164, 0, 0, 152, 0, 0, 0, 15,
        3, 0, 0, 55, 4, 0, 0, 31, 216, 0, 0, 200, 0, 0, 0, 15, 3, 0, 0, 98, 4, 0, 0, 23, 244, 0, 0,
        216, 0, 0, 0, 15, 3, 0, 0, 98, 4, 0, 0, 56, 244, 0, 0, 224, 0, 0, 0, 15, 3, 0, 0, 98, 4, 0,
        0, 35, 244, 0, 0, 232, 0, 0, 0, 15, 3, 0, 0, 163, 4, 0, 0, 21, 4, 1, 0, 240, 0, 0, 0, 15,
        3, 0, 0, 163, 4, 0, 0, 30, 4, 1, 0, 8, 1, 0, 0, 15, 3, 0, 0, 163, 4, 0, 0, 27, 4, 1, 0, 16,
        1, 0, 0, 15, 3, 0, 0, 205, 4, 0, 0, 12, 176, 1, 0, 32, 1, 0, 0, 15, 3, 0, 0, 252, 4, 0, 0,
        10, 16, 1, 0, 80, 1, 0, 0, 15, 3, 0, 0, 72, 5, 0, 0, 9, 20, 1, 0, 88, 1, 0, 0, 15, 3, 0, 0,
        86, 5, 0, 0, 17, 24, 1, 0, 104, 1, 0, 0, 15, 3, 0, 0, 86, 5, 0, 0, 23, 24, 1, 0, 112, 1, 0,
        0, 15, 3, 0, 0, 127, 5, 0, 0, 9, 32, 1, 0, 168, 1, 0, 0, 15, 3, 0, 0, 155, 5, 0, 0, 37, 48,
        1, 0, 176, 1, 0, 0, 15, 3, 0, 0, 155, 5, 0, 0, 23, 48, 1, 0, 192, 1, 0, 0, 15, 3, 0, 0,
        198, 5, 0, 0, 25, 52, 1, 0, 216, 1, 0, 0, 15, 3, 0, 0, 198, 5, 0, 0, 23, 52, 1, 0, 224, 1,
        0, 0, 15, 3, 0, 0, 234, 5, 0, 0, 37, 56, 1, 0, 232, 1, 0, 0, 15, 3, 0, 0, 234, 5, 0, 0, 23,
        56, 1, 0, 240, 1, 0, 0, 15, 3, 0, 0, 21, 6, 0, 0, 25, 60, 1, 0, 8, 2, 0, 0, 15, 3, 0, 0,
        21, 6, 0, 0, 23, 60, 1, 0, 16, 2, 0, 0, 15, 3, 0, 0, 57, 6, 0, 0, 5, 64, 1, 0, 160, 2, 0,
        0, 15, 3, 0, 0, 205, 6, 0, 0, 10, 72, 1, 0, 232, 2, 0, 0, 15, 3, 0, 0, 27, 7, 0, 0, 9, 76,
        1, 0, 240, 2, 0, 0, 15, 3, 0, 0, 40, 7, 0, 0, 13, 84, 1, 0, 248, 2, 0, 0, 15, 3, 0, 0, 40,
        7, 0, 0, 19, 84, 1, 0, 24, 3, 0, 0, 15, 3, 0, 0, 205, 4, 0, 0, 12, 176, 1, 0, 32, 3, 0, 0,
        15, 3, 0, 0, 79, 7, 0, 0, 11, 108, 1, 0, 88, 3, 0, 0, 15, 3, 0, 0, 205, 4, 0, 0, 12, 176,
        1, 0, 104, 3, 0, 0, 15, 3, 0, 0, 116, 7, 0, 0, 1, 180, 1, 0, 16, 0, 0, 0, 201, 7, 0, 0, 20,
        0, 0, 0, 8, 0, 0, 0, 2, 0, 0, 0, 118, 7, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 2, 0, 0, 0, 123, 7,
        0, 0, 0, 0, 0, 0, 48, 0, 0, 0, 19, 0, 0, 0, 128, 7, 0, 0, 0, 0, 0, 0, 80, 0, 0, 0, 24, 0,
        0, 0, 132, 7, 0, 0, 0, 0, 0, 0, 104, 0, 0, 0, 24, 0, 0, 0, 136, 7, 0, 0, 0, 0, 0, 0, 120,
        0, 0, 0, 24, 0, 0, 0, 140, 7, 0, 0, 0, 0, 0, 0, 216, 0, 0, 0, 2, 0, 0, 0, 118, 7, 0, 0, 0,
        0, 0, 0, 232, 0, 0, 0, 29, 0, 0, 0, 148, 7, 0, 0, 0, 0, 0, 0, 88, 1, 0, 0, 34, 0, 0, 0,
        156, 7, 0, 0, 0, 0, 0, 0, 128, 1, 0, 0, 29, 0, 0, 0, 161, 7, 0, 0, 0, 0, 0, 0, 168, 1, 0,
        0, 29, 0, 0, 0, 161, 7, 0, 0, 0, 0, 0, 0, 176, 1, 0, 0, 29, 0, 0, 0, 161, 7, 0, 0, 0, 0, 0,
        0, 184, 1, 0, 0, 29, 0, 0, 0, 169, 7, 0, 0, 0, 0, 0, 0, 216, 1, 0, 0, 29, 0, 0, 0, 169, 7,
        0, 0, 0, 0, 0, 0, 224, 1, 0, 0, 29, 0, 0, 0, 177, 7, 0, 0, 0, 0, 0, 0, 232, 1, 0, 0, 29, 0,
        0, 0, 177, 7, 0, 0, 0, 0, 0, 0, 8, 2, 0, 0, 29, 0, 0, 0, 148, 7, 0, 0, 0, 0, 0, 0, 24, 2,
        0, 0, 29, 0, 0, 0, 177, 7, 0, 0, 0, 0, 0, 0, 72, 2, 0, 0, 29, 0, 0, 0, 148, 7, 0, 0, 0, 0,
        0, 0, 240, 2, 0, 0, 34, 0, 0, 0, 156, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 3, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0,
        138, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 9, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 208, 0, 0, 0,
        0, 0, 0, 0, 240, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 24,
        0, 0, 0, 0, 0, 0, 0, 17, 0, 0, 0, 1, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 192, 1, 0, 0, 0, 0, 0, 0, 112, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 20, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 48, 5, 0, 0, 0, 0, 0, 0, 41, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 28, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 89, 5, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 117, 0, 0, 0, 9, 0, 0, 0, 64,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 96, 5, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0,
        0, 2, 0, 0, 0, 3, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 124, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 160, 5, 0, 0, 0, 0, 0, 0, 172,
        14, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 129, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 80, 20, 0, 0,
        0, 0, 0, 0, 12, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0,
    ];
}
